class BodyName:
    Continuous_line = "Continuous Line"
    Broken_line = "Broken Line"
    Side_walk = "Side Walk"
    Ground = "Ground"
    Ego_vehicle = "Ego Vehicle"
    Ego_vehicle_top = "Ego Vehicle Top"
    Traffic_vehicle = "Traffic Vehicle"
    Lane = "Lane"
    Traffic_cone = "Traffic Cone"
    Traffic_triangle = "Traffic Triangle"
