class MetaDriveSceneElement:
    """
    Follow waymo style
    """

    LANE_CENTER_LINE = "LANE_SURFACE_STREET"
    CONTINUOUS_YELLOW_LINE = "ROAD_LINE_SOLID_SINGLE_YELLOW"
    CONTINUOUS_GREY_LINE = "ROAD_LINE_SOLID_SINGLE_WHITE"
    BROKEN_GREY_LINE = "ROAD_LINE_BROKEN_SINGLE_WHITE"
    BROKEN_YELLOW_LINE = "BROKEN_SINGLE_YELLOW"
